/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Created an API key
 */
export class ApiKeyCreateResponse extends SpeakeasyBase {
    /**
     * The API key ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * The generated 64-bit token required to access the Neon API
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;
}
