/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Type of subscription to Neon Cloud.
 *
 * @remarks
 * Notice that for users without billing account this will be "UNKNOWN"
 *
 */
export enum BillingSubscriptionType {
  Unknown = "UNKNOWN",
  Free = "free",
  Pro = "pro",
  PlatformPartnership = "platform_partnership",
  Enterprise = "enterprise",
}
