/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Branch } from "./branch";
import { Expose, Type } from "class-transformer";

/**
 * Returned information about the specified branch
 */
export class BranchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "branch" })
  @Type(() => Branch)
  branch: Branch;
}
