/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Branch } from "./branch";
import { Operation } from "./operation";
import { Expose, Type } from "class-transformer";

/**
 * Deleted the specified branch
 */
export class BranchOperations extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "branch" })
  @Type(() => Branch)
  branch: Branch;

  @SpeakeasyMetadata({ elemType: Operation })
  @Expose({ name: "operations" })
  @Type(() => Operation)
  operations: Operation[];
}
