/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Branch } from "./branch";
import { Expose, Type } from "class-transformer";

/**
 * Returned a list of branches for the specified project
 */
export class BranchesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Branch })
    @Expose({ name: "branches" })
    @Type(() => Branch)
    branches: Branch[];
}
