/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Database } from "./database";
import { Expose, Type } from "class-transformer";

/**
 * Returned the database details
 */
export class DatabaseResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "database" })
    @Type(() => Database)
    database: Database;
}
