/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class Database extends SpeakeasyBase {
  /**
   * The ID of the branch to which the database belongs
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "branch_id" })
  branchId: string;

  /**
   * A timestamp indicating when the database was created
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * The database ID
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: number;

  /**
   * The database name
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The name of role that owns the database
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "owner_name" })
  ownerName: string;

  /**
   * A timestamp indicating when the database was last updated
   *
   * @remarks
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "updated_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  updatedAt: Date;
}
