/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Database } from "./database";
import { Operation } from "./operation";
import { Expose, Type } from "class-transformer";

/**
 * Created a database in the specified branch
 */
export class DatabaseOperations extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "database" })
  @Type(() => Database)
  database: Database;

  @SpeakeasyMetadata({ elemType: Operation })
  @Expose({ name: "operations" })
  @Type(() => Operation)
  operations: Operation[];
}
