/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Database } from "./database";
import { Expose, Type } from "class-transformer";

/**
 * Returned a list of databases of the specified branch
 */
export class DatabasesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Database })
    @Expose({ name: "databases" })
    @Type(() => Database)
    databases: Database[];
}
