/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A collection of settings for a Neon endpoint
 */
export class DefaultEndpointSettings extends SpeakeasyBase {
    /**
     * A raw representation of PostgreSQL settings
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pg_settings" })
    pgSettings?: Record<string, string>;
}
