/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The compute endpoint type. Either `read_write` or `read_only`.
 *
 * @remarks
 * The `read_only` compute endpoint type is not yet supported.
 *
 */
export enum EndpointType {
  ReadOnly = "read_only",
  ReadWrite = "read_write",
}
