/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Endpoint } from "./endpoint";
import { Operation } from "./operation";
import { Expose, Type } from "class-transformer";

/**
 * Created an endpoint
 */
export class EndpointOperations extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "endpoint" })
  @Type(() => Endpoint)
  endpoint: Endpoint;

  @SpeakeasyMetadata({ elemType: Operation })
  @Expose({ name: "operations" })
  @Type(() => Operation)
  operations: Operation[];
}
