/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The connection pooler mode. Neon supports PgBouncer in `transaction` mode only.
 *
 * @remarks
 *
 */
export enum EndpointPoolerMode {
  Transaction = "transaction",
}
