/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Endpoint } from "./endpoint";
import { Expose, Type } from "class-transformer";

/**
 * Returned a list of endpoints for the specified branch
 */
export class EndpointsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Endpoint })
    @Expose({ name: "endpoints" })
    @Type(() => Endpoint)
    endpoints: Endpoint[];
}
