/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The state of the compute endpoint
 *
 * @remarks
 *
 */
export enum EndpointState {
  Init = "init",
  Active = "active",
  Idle = "idle",
}
