/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Endpoint } from "./endpoint";
import { Expose, Type } from "class-transformer";

/**
 * Returned information about the specified endpoint
 */
export class EndpointResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "endpoint" })
  @Type(() => Endpoint)
  endpoint: Endpoint;
}
