/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The status of the operation
 */
export enum OperationStatus {
    Running = "running",
    Finished = "finished",
    Failed = "failed",
    Scheduling = "scheduling",
}
