/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Operation } from "./operation";
import { Expose, Type } from "class-transformer";

/**
 * Returned details for the specified operation
 */
export class OperationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "operation" })
    @Type(() => Operation)
    operation: Operation;
}
