/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The action performed by the operation
 */
export enum OperationAction {
    CreateCompute = "create_compute",
    CreateTimeline = "create_timeline",
    StartCompute = "start_compute",
    SuspendCompute = "suspend_compute",
    ApplyConfig = "apply_config",
    CheckAvailability = "check_availability",
    DeleteTimeline = "delete_timeline",
    CreateBranch = "create_branch",
    TenantIgnore = "tenant_ignore",
    TenantAttach = "tenant_attach",
    TenantDetach = "tenant_detach",
    TenantReattach = "tenant_reattach",
    ReplaceSafekeeper = "replace_safekeeper",
    DisableMaintenance = "disable_maintenance",
}
