/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillingSubscriptionType } from "./billingsubscriptiontype";
import { Expose } from "class-transformer";

export class ProjectOwnerData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "branches_limit" })
    branchesLimit: number;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * Type of subscription to Neon Cloud.
     *
     * @remarks
     * Notice that for users without billing account this will be "UNKNOWN"
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subscription_type" })
    subscriptionType: BillingSubscriptionType;
}
