/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Operation } from "./operation";
import { Project } from "./project";
import { Expose, Type } from "class-transformer";

/**
 * Updated the specified project
 */
export class ProjectOperations extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Operation })
  @Expose({ name: "operations" })
  @Type(() => Operation)
  operations: Operation[];

  @SpeakeasyMetadata()
  @Expose({ name: "project" })
  @Type(() => Project)
  project: Project;
}
