/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The Neon compute provisioner.
 *
 * @remarks
 *
 */
export enum Provisioner {
    K8sPod = "k8s-pod",
    K8sNeonvm = "k8s-neonvm",
}
