/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Role } from "./role";
import { Expose, Type } from "class-transformer";

/**
 * Successfully returned details for the specified role
 */
export class RoleResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  @Type(() => Role)
  role: Role;
}
