/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successfully returned password for the specified role
 */
export class RolePasswordResponse extends SpeakeasyBase {
    /**
     * The role password
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "password" })
    password: string;
}
