/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Operation } from "./operation";
import { Role } from "./role";
import { Expose, Type } from "class-transformer";

/**
 * Created a role in the specified branch
 */
export class RoleOperations extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Operation })
    @Expose({ name: "operations" })
    @Type(() => Operation)
    operations: Operation[];

    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    @Type(() => Role)
    role: Role;
}
