/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Role } from "./role";
import { Expose, Type } from "class-transformer";

/**
 * Returned a list of roles from the specified branch.
 */
export class RolesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Role })
  @Expose({ name: "roles" })
  @Type(() => Role)
  roles: Role[];
}
