/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateProjectBranchRoleRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    roleCreateRequest: shared.RoleCreateRequest;

    /**
     * The branch ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=branch_id" })
    branchId: string;

    /**
     * The Neon project ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;
}

export class CreateProjectBranchRoleResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * General Error
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    /**
     * Created a role in the specified branch
     */
    @SpeakeasyMetadata()
    roleOperations?: shared.RoleOperations;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
