/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteProjectBranchRequest extends SpeakeasyBase {
  /**
   * The branch ID
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=branch_id",
  })
  branchId: string;

  /**
   * The Neon project ID
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=project_id",
  })
  projectId: string;
}

export class DeleteProjectBranchResponse extends SpeakeasyBase {
  /**
   * Deleted the specified branch
   */
  @SpeakeasyMetadata()
  branchOperations?: shared.BranchOperations;

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * General Error
   */
  @SpeakeasyMetadata()
  generalError?: shared.GeneralError;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
