/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetProjectBranchRolePasswordRequest extends SpeakeasyBase {
    /**
     * The branch ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=branch_id" })
    branchId: string;

    /**
     * The Neon project ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;

    /**
     * The role name
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=role_name" })
    roleName: string;
}

export class GetProjectBranchRolePasswordResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Role not found
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    /**
     * Successfully returned password for the specified role
     */
    @SpeakeasyMetadata()
    rolePasswordResponse?: shared.RolePasswordResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
