/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetProjectBranchDatabaseRequest extends SpeakeasyBase {
    /**
     * The branch ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=branch_id" })
    branchId: string;

    /**
     * The database name
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=database_name" })
    databaseName: string;

    /**
     * The Neon project ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;
}

export class GetProjectBranchDatabaseResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Returned the database details
     */
    @SpeakeasyMetadata()
    databaseResponse?: shared.DatabaseResponse;

    /**
     * General Error
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
