/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetProjectEndpointRequest extends SpeakeasyBase {
    /**
     * The endpoint ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=endpoint_id" })
    endpointId: string;

    /**
     * The Neon project ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;
}

export class GetProjectEndpointResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Returned information about the specified endpoint
     */
    @SpeakeasyMetadata()
    endpointResponse?: shared.EndpointResponse;

    /**
     * General Error
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
