/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListProjectBranchDatabasesRequest extends SpeakeasyBase {
    /**
     * The branch ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=branch_id" })
    branchId: string;

    /**
     * The Neon project ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=project_id" })
    projectId: string;
}

export class ListProjectBranchDatabasesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Returned a list of databases of the specified branch
     */
    @SpeakeasyMetadata()
    databasesResponse?: shared.DatabasesResponse;

    /**
     * General Error
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
