/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ResetProjectBranchRolePasswordRequest extends SpeakeasyBase {
  /**
   * The branch ID
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=branch_id",
  })
  branchId: string;

  /**
   * The Neon project ID
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=project_id",
  })
  projectId: string;

  /**
   * The role nam
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=role_name",
  })
  roleName: string;
}

export class ResetProjectBranchRolePasswordResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * General Error
   */
  @SpeakeasyMetadata()
  generalError?: shared.GeneralError;

  /**
   * Reset the passsword for the specified role
   */
  @SpeakeasyMetadata()
  roleOperations?: shared.RoleOperations;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
