/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RevokeApiKeyRequest extends SpeakeasyBase {
    /**
     * The API key ID
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=key_id" })
    keyId: number;
}

export class RevokeApiKeyResponse extends SpeakeasyBase {
    /**
     * Revoked the specified API key
     */
    @SpeakeasyMetadata()
    apiKeyRevokeResponse?: shared.ApiKeyRevokeResponse;

    @SpeakeasyMetadata()
    contentType: string;

    /**
     * General Error
     */
    @SpeakeasyMetadata()
    generalError?: shared.GeneralError;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
